# Site settings
title: Storage World 
SEOTitle: 鱼鱼的博客
header-img: img/post-bg-desk.jpeg
email: penglaiyxy@gmail.com
description: "Every failure is leading towards success."
keyword: " 鱼鱼的博客, penglaiyxy, ceph, bigdata, distribute system"
url: "http://penglaiyxy.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/penglaiyxy/penglaiyxy.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/penglaiyxy.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# SNS settings
RSS: false
# weibo_username:     
# zhihu_username:     
github_username:    penglaiyxy
# facebook_username:  
# jianshu_username:   
# twitter_username:   




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 7bcce1754500cdfad5ee                            #生成的clientID
  clientSecret: 6b0efac96bb70618849d2120e3bf48088001287b    #生成的clientSecret
  repo: penglaiyxy.github.io    #仓库名称
  owner: penglaiyxy    #github用户名
  admin: penglaiyxy
  id: md5(location.href)
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 77a4d472db1c01633d753f9140c77455

# Google Analytics
ga_track_id: 'UA-118742586-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "吴忠杰博士的存储之道",
        href: "http://blog.51cto.com/alanwu"
    },{
        title: "ictfox blog/ceph technology",
        href: "http://www.yangguanjun.com"
    },{
        title: "Eric/ceph technology",
        href: "http://blog.wjin.org"
    },{
        title: "徐小胖/ceph",
        href: "http://www.xuxiaopang.com"
    },{
	title: "磨磨/ceph",
        href: "http://www.zphj1987.com"
    }
]
